# ======================== Elasticsearch Configuration =========================
#
# NOTE: Elasticsearch comes with reasonable defaults for most settings.
#       Before you set out to tweak and tune the configuration, make sure you
#       understand what are you trying to accomplish and the consequences.
#
# The primary way of configuring a node is via this file. This template lists
# the most important settings you may want to configure for a production cluster.
#
# Please consult the documentation for further information on configuration options:
# https://www.elastic.co/guide/en/elasticsearch/reference/index.html
#
# ---------------------------------- Cluster -----------------------------------
#
# Use a descriptive name for your cluster:
#
#cluster.name: "1"
cluster.name: my-application
#
# ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#
#node.name: node-1
node.name: node-1
#
# Add custom attributes to the node:
#
#node.attr.rack: r1
node.attr.temperature: hot
# ----------------------------------- Paths ------------------------------------
#
# Path to directory where to store the data (separate multiple locations by comma):
#
#path.data: /path/to/data
path.data: /data/elk/elasticsearch/data
# Path to log files:
#
#path.logs: /path/to/logs
path.logs: /data/elk/elasticsearch/logs
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
#bootstrap.memory_lock: true
bootstrap.memory_lock: false
bootstrap.system_call_filter: false
# Make sure that the heap size is set to about half the memory available
# on the system and that the owner of the process is allowed to use this
# limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
#network.host: 192.168.0.1
network.host: node-1
network.publish_host: node-1
# Set a custom port for HTTP:
#
#http.port: 9200
http.port: 9200
# For more information, consult the network module documentation.
transport.tcp.port: 9300
transport.tcp.compress: true
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when this node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
#discovery.seed_hosts: ["host1", "host2"]
#
# Bootstrap the cluster using an initial set of master-eligible nodes:
#
#cluster.initial_master_nodes: ["node-1", "node-2"]
discovery.zen.ping.unicast.hosts: [unicasthosts]

cluster.initial_master_nodes: [master.hosts]
# For more information, consult the discovery and cluster formation module documentation.
#
# ---------------------------------- Gateway -----------------------------------
#
# Block initial recovery after a full cluster restart until N nodes are started:
#
#gateway.recover_after_nodes: 3
#
# For more information, consult the gateway module documentation.
#
# ---------------------------------- Various -----------------------------------
#
# Require explicit names when deleting indices:
#
#action.destructive_requires_name: true
#
action.auto_create_index: .security,.security-6,.monitoring*,.watches,.triggered_watches,.watcher-history*,logstash*,Emar*,filebeat-*,packetbeat-*,metricbeat-*,apm-*,netflow-*,elastiflow-*,+i*,+s*,+all*,+en*,+data*,+register*

##
http.cors.enabled: true
http.cors.allow-origin: "*"



#xpack.security.enabled: false
#xpack.monitoring.enabled
#xpack.graph.enabled
#xpack.watcher.enabled
#thread_pool.bulk.type: fixed



##
#thread_pool.bulk.size: 200
##
thread_pool.get.queue_size: 2000
thread_pool.write.queue_size: 2000
thread_pool.analyze.queue_size: 2000
thread_pool.search.queue_size: 2000
thread_pool.listener.queue_size: 2000

#elasticflow
indices.query.bool.max_clause_count: 8192
search.max_buckets: 250000
#
#xpack.monitoring.ui.container.elasticsearch.enabled: true
